# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todo-take-cantik

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://acr20220514alterbooth1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_28523e93fb024a7dbf64fb0d1551151a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8139a6472b1f40c5b2f57514b8b1b3fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: acr20220514alterbooth1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_28523e93fb024a7dbf64fb0d1551151a }}/hello-world-take-cantik:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-take-cantik'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c7ed582ebe94453a037e2158228a39f }}
        images: 'acr20220514alterbooth1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_28523e93fb024a7dbf64fb0d1551151a }}/hello-world-take-cantik:${{ github.sha }}'